### ISSUE TITLE
Provide Installation Instructions

### ISSUE THREAD

**Issue by Pitastic** [chifflier/nfqueue-bindings#3]
I'm unsure if this project is still alive - I give it a try anyway.

This is how I installed it:

```
$ apt install libnetfilter-queue-dev
$ git clone https://github.com/chifflier/nfqueue-bindings.git
$ mkdir build
$ cd nfqueue-bindings
$ cmake . -B ../build
$ cd ../build
$ make
$ make install
```

It seems to be installed but how can I check this?

```
$ locate nfqueue
/usr/src/linux-headers-5.4.0-58-generic/include/config/netfilter/xt/target/nfqueue.h
```

I needed this package for INetSim but this gives me still the same error:

```
* redirect - failed! Error: Sorry, this module requires the perl nfqueue-bindings!
```

So not sure if everything was right...

**Comment by qux-bbb** [comment]
@Pitastic ，if you want to install InetSim，you can run the following commands:  
```
$ sudo su
$ echo "deb http://www.inetsim.org/debian/ binary/" > /etc/apt/sources.list.d/inetsim.list
$ wget -O - http://www.inetsim.org/inetsim-archive-signing-key.asc | apt-key add -
$ apt update
$ apt install inetsim
```
from https://blog.christophetd.fr/malware-analysis-lab-with-virtualbox-inetsim-and-burp/#INetSim

**Comment by Pitastic** [comment]
Thanks. INetSim is already up and running (installed via apt). But the bindings are not as they aren't listed as a dependency in apt.

In order to use the `redirect` feature from INetSim I have to install the bindings from this repo as stated here in the docs (https://www.inetsim.org/requirements.html).

**Comment by apollo789** [comment]
@Pitastic 

![image](https://user-images.githubusercontent.com/28105516/104687585-76ee9900-573a-11eb-9148-ae2f8657e3ae.png)

![image](https://user-images.githubusercontent.com/28105516/104687784-d056c800-573a-11eb-8f79-05d7ad7e3ec4.png)

![image](https://user-images.githubusercontent.com/28105516/104687989-32afc880-573b-11eb-9950-27b89af2ab28.png)
